### ISSUE TITLE
TypeError- othertokenregex.test is not a function

### ISSUE THREAD

**Issue by prompt-sync** [Combo-Miner/Repl-Scrapper#1]
ok

**Comment by Combo-Miner** [comment]
Hello,make you sure that u  didnt write a right regex this will not work

**Comment by prompt-sync** [comment]
can you give me an example of regex

**Comment by prompt-sync** [comment]
/MTE/ ?

**Comment by Combo-Miner** [comment]
Yeah sure if u want to lear more about regex: https://builtin.com/software-engineering-perspectives/javascript-regex#:~:text=a%20regular%20expression.-,For%20example%3A,Is%20the%20actual%20string%20passed.

**Comment by prompt-sync** [comment]
Thank you so much

**Comment by prompt-sync** [comment]
quick question, what is the regex that you use, every one i try just doesn't work, also do u have like a discord server for this project? if so please can you invite me.
